### ISSUE TITLE
Over 100% uploaded?

### ISSUE THREAD

**Issue by arjones85** [haiwen/seafile-client#875] opened 2017-02-17 18:04 UTC
I added a large amount of files to a library all at once, and am getting feedback from the client showing over 100% synced. Thoughts?

![over100](https://cloud.githubusercontent.com/assets/8582158/23077221/3e969fae-f509-11e6-8596-2f6c8c0ce861.jpg)

**Comment by killing** [comment] 2017-02-18 02:09
Are you using the latest version? On which OS? This may be some edge case bug caused by our recent change to upload progress. Could you send me the seafile.log file? Thanks

**Comment by arjones85** [comment] 2017-02-18 06:46
Hello,

Yes, Seafile server 6.0.8 on Linux, desktop sync client 6.0.3 on Windows 10. After it reached 215% done I closed the client out, reopened it back up, and it finished syncing with the correct percentage being shown. The files also transferred properly.

What I did specifically before it showed the invalid percentage is I cloned a git repo directly into a folder inside one of my libraries.

Logs can be found here: http://pastebin.com/c3iVRM6E

Thanks!

**Comment by killing** [comment] 2017-02-21 08:24
Thanks for reporting. I've found one possible cause of the problem and fixed it in version 6.0.4. You can try it once it's released.

**Comment by Rojetto** [comment] 2017-06-05 18:38
Hi, I still see this happen regularly on my system when adding multiple moderately sized files to a library. I'm using Seafile Client 6.0.6 on Windows and Seafile Server for Raspberry Pi 6.0.6.
![seafile_mehrals100](https://cloud.githubusercontent.com/assets/777285/26797872/bc05b14e-4a2e-11e7-9b01-2d6bbebfa075.PNG)

**Comment by killing** [comment] 2017-07-11 14:20
@Rojetto Can you still reproduce the problem? The problem still sometimes bother users. If you can provide detailed steps for reproducing it, we'll appreciate.

**Comment by shoeper** [comment] 2018-05-30 10:58
Closing because there is no further response.

**Closed by shoeper** 2018-05-30 10:58 UTC
