### ISSUE TITLE
Client don't try to reconnect when loosing internet connection for only one minute

### ISSUE THREAD

**Issue by tuxayo** [haiwen/seafile-client#782] opened 2016-03-02 08:41 UTC
I regularly find the client in disconnected state and I have to relaunch it manually.

After some tests, an internet connection loss of about one minute is enough to make the client switch to this state.

It should try regularly to reconnect every few minutes to avoid staying disconnected until the user notices it.

**Comment by killing** [comment] 2016-03-17 06:31
Can you give us a screenshot of the seafile-applet window? and what can you see in the seafile.log?

**Comment by killing** [comment] 2016-03-17 06:32
The syncing engine (seaf-daemon) should have handled connection lose situations. It'll timeout the connection if no data is transferred after 45 seconds (in older versions) or 120 seconds (in the latest version).

**Comment by tuxayo** [comment] 2016-03-21 10:31
![sans titre](https://cloud.githubusercontent.com/assets/2678215/13915945/ebf073cc-ef57-11e5-9ffb-fe3a83bd602e.png)
[logs](https://zerobin.guillaume-leduc.fr/?42df6be766eaa35a#RKR9peMfXotlZerFm3alV2OcbGYzWYPgcgBt/6TGUTM=)

It's turns out that it's actually a problem with the UI icons not reflecting the sync state. Sorry for not having checked more deeply.

Should I rename the issue? (I'm not sure how to describe it now)

**Comment by shoeper** [comment] 2016-03-21 13:23
I can confirm it. It seems to be a linux specific issues. It occurs on Fedora 23 here but not on Windows 7, 8.1, 10.

**Comment by silberzwiebel** [comment] 2016-04-11 09:26
Not sure, if I'm right here, but I think I ran into the same issue. My use-case:
seafile starts automatically on my Fedora 23 laptop, seafile-client version 5.0.7 from the pkerling copr repo. If there is internet connection (WiFi), everything works fine. If I then turn off the WiFi, and turn it later on, seafile does not connect to the server. In the applet.log there are messages every 30 seconds or so reading like this:
`network error for https://[seafile-server-domain]/api2/ping: network access is disabled.`
If I manually close seafile and start it again, it works.

**Comment by shoeper** [comment] 2016-05-20 14:20
This is a duplicate of https://github.com/haiwen/seafile-client/issues/759

**Closed by shoeper** 2016-05-20 14:20 UTC
