### ISSUE TITLE
Client doesn't work with multiple users Mac OS

### ISSUE THREAD

**Issue by tafoya** [haiwen/seafile-client#669] opened 2015-07-12 21:01 UTC
We have a shared Mac at home. Each user's ccnet.conf has a unique port specified. However, when a user opens the Seafile Client after an instance has already been started by another user (logged in, fast user switching), a popup saying "Found another running process of Seafile, kill it and start a new one?". Clicking yes does nothing. 

On a side note, the seafile client works great in a multiuser environment on a Windows machine after unique ports are assigned to users.

**Comment by shoeper** [comment] 2015-07-12 21:54
Just as a note: If you had to asign manual ports this should also definetly be changed to something automatic (e.g. use next port if current port is already in use).

**Comment by stefanandres** [comment] 2015-12-13 15:18
Yes, please fix that.

**Comment by beng81** [comment] 2016-02-09 18:58
This issue also bothers me for quite a while now and I thought maybe it gets fixed soon. But with Version 5.0.3 I still face the same issues. Is there a possibility to fix that? I think the issue #122 might be a duplicate.

**Comment by giovannipizzi** [comment] 2016-02-11 10:23
I'd also like to support this issue (reproduced with the Mac client v. 5.0.3), and agree that it's probably a duplicate of #122.

I assume that there is no reason for which two users cannot run two seafile clients (I'm pretty sure they run with user credentials), so my gut feeling is just that the check (to see if another process is running) is checking any process on the machine rather than only same-user processes.

I gave a look at the code, and even if I'm not expert of C++ and system-level calls, that's my understanding (maybe wrong) of why the behavior is different from Windows, and how to fix the Mac version:

- on Windows, `process_is_running` (in `src/utils/process-win.cpp`) calls `get_process_handle` that calls the Windows function `OpenProcess` with flags (among others) `PROCESS_TERMINATE | PROCESS_VM_READ`. My guess is that Windows does not return processes that do not belong to the user as he could not terminate or read their memory - as a result, on Windows one gets the message only if the same user is already running Seafile client.

- on Mac, `process_is_running` in `src/utils/process-mac.cpp` calls `getBSDProcessPid` that calls `GetBSDProcessList` that calls the system-level `sysctl` function, that I believe returns all processes running in the machine, which is the cause of this issue. My suggestion is that `getBSDProcessPid` should not check only for identical name, but for same user (I guess one could user `proc->eproc.e_pcred->p_ruid` or something else to get the process user id, but someone more experienced may give a better advice - I never used `sysctl`).

It would be great if some this issue could be addressed soon, as it is quite a big problem for me (it makes sense to use seafile for me only I can use it at the same time with ultiple Mac users). Thanks!

**Comment by beng81** [comment] 2016-03-24 17:27
With the hints from giovannipizzi I tried to setup the build environment on my mac and could fix it on my system. I hope it can be reviewed and accepted for the next version.

**Comment by freeplant** [comment] 2016-03-25 02:57
It will be available in the next release.

**Closed by freeplant** 2016-03-25 02:57 UTC
