### ISSUE TITLE
Logfiles grow over time without any rotation

### ISSUE THREAD

**Issue by allo-** [haiwen/seafile-client#866] opened 2017-02-11 20:05 UTC
I found ``.ccnet/logs/applet.log`` to have 105 MB and ``.ccnet/logs/seafile.log`` with 25MB, containing log entries from 2013. It seems, that the logfiles are growing over time and are never deleted or rotated.

**Comment by shoeper** [comment] 2017-02-11 22:11
Duplicate of #800

**Closed** 2017-02-11 23:00 UTC
