### ISSUE TITLE
how to build seafile-client on mac for windows

### ISSUE THREAD

**Issue by carol881221** [haiwen/seafile-client#848] opened 2016-12-04 16:03 UTC
I compile the seafile-client sourse only generated seafile-applet file which only can be  installed on os system. Who can tell me how to build seafile-client on mac for windows.

**Comment by shoeper** [comment] 2018-10-29 21:49
Duplicate of https://github.com/haiwen/seafile-client/issues/810

**Closed by shoeper** 2018-10-29 21:49 UTC

**Comment by wangwei19900725** [comment] 2019-02-21 03:47
> I compile the seafile-client sourse only generated seafile-applet file which only can be installed on os system. Who can tell me how to build seafile-client on mac for windows.

I need make a dmg package to publish in stores,but I cannnot find the right way,can you give some tips.
