### ISSUE TITLE
Global percentage on client while syncing

### ISSUE THREAD

**Issue by timonoj** [haiwen/seafile-client#453] opened 2015-02-10 03:32 UTC
Hi guys,

Not sure if this files as a bug, more of a GUI usability issue, but anyhow: Whenever the client is syncing, could you make it show the global percentage of the upload/download at task? Currently I understand it only shows the percentage of the file being currently uploaded.

By the way, if possible could you add the option for the client to show somewhere (even if it's just a toaster when the mouse hovers over the status) which one is the current file uploaded? It can be confusing to follow what the client might be doing at any given time (i.e, syncing out of the blue with no recent changes, and you can only get to see the percentage for unknown files that keeps getting back to 0 after reaching 100%).

**Comment by Jip-Hop** [comment] 2015-02-16 20:59
I agree with timonoj that it would be great to have a global percentage of the sync process. I'm not sure if that's possible with the current way folders are indexed though.

But I recon it should be easily possible to show what file is being uploaded/downloaded. That would be a really useful feature, both for debugging as for regular usage. I'm often wondering what the client is actually syncing.

**Comment by dportabella** [comment] 2016-03-07 10:02
+1

**Comment by shoeper** [comment] 2018-10-29 22:09
duplicate of #60

**Closed by shoeper** 2018-10-29 22:09 UTC
Labels: PR-no-schedule, bug-user-experience
