### ISSUE TITLE
On Linux, every time I edit a file, seafile pegs a CPU core for 50 seconds

### ISSUE THREAD

**Issue by cpbotha** [haiwen/seafile-client#220] opened 2014-09-25 06:52 UTC
I'm currently evaluating seafile via a subscription to seacloud.cc. I have synced up a 13GB library with about 150k files in encrypted mode.

Every time I save to a text file that I'm editing locally, the "seaf-daemon" process uses 100% of a whole i7 core for about 50 seconds. In the UI, it claims that it's indexing files. This is on an Intel 520 SSD. This would otherwise not be such an issue, but this is a laptop, and indexing 150k files every time I save a small text change is going to kill the battery.

Why does seafile have to re-index every single time that I save changes to a small text file?

**Comment by pglez82** [comment] 2015-01-24 17:16
I can confirm the same behaviour here. Im running version 4.0.6 in linux. It takes about 4 minutes indexing files each time I change something. My repository is about 100GB.
I'm looking forward to testing the 4.1 version. Thank you! Pablo

**Comment by morloy** [comment] 2015-03-20 11:05
The seafile client 4.1.1 on Linux still shows this behavior.

Unfortunately, this makes seafile almost unusable, since my CPU is running on 100% almost constantly, due to seafile "indexing files" all the time.

**Comment by pglez82** [comment] 2015-05-18 17:10
I was making a few more tests with seafile. Aflter a while I discovered that the main problem are the number of files. I had 100Gb in 300k files. I took about 4 minutes to index my files each time. I decided then to tar the data that I didn't use a lot. Now I have 50k files (same data 100Gb, but in less files). Surprisingly, it takes now less that 10 seconds to synchronize. So this process doesn't depend on the size of the folder but on the number of files. It works great now!

**Comment by Splatter** [comment] 2015-06-09 21:33
This is still a major problem for us and, regrettably, we've already dismantled our Dropbox setup in favor of Seafile.  Now, where Dropbox was handling this number of files without a problem, Seafile is taking one of our smaller AWS Windows server instances to 100% CPU usage for hours and hours at a time.

We're running Seafile on a Linux server with many Windows clients.  One library has well over 200,000 files and is actively added to and modified. There are four Windows servers that are synced to that folder.  Even the slightest change to the folder requires periodic reindexing (where the progress stays at 0% the whole time) and downloading.  On one machine the downloading is VERY slow (nothing is using either the bandwidth or CPU other than Seafile) and uses nowhere near the available bandwidth both the client and server have available to it.

Did I move us from Dropbox too soon??

**Comment by killing** [comment] 2015-06-10 02:40
We're well aware of the issue. However we have many other tasks at hand right now. You can expect this to be fixed in about a month.

**Comment by fa72bd53** [comment] 2015-11-28 23:21
thinking about buying a seacloud licence. is this issue really still open? :(

**Comment by freeplant** [comment] 2015-11-29 04:55
The problem is already solved. See our benchmark https://seacloud.cc/group/3/wiki/seafile-syncing-performance/

**Closed by freeplant** 2015-11-29 04:55 UTC
Labels: platform-linux
