### ISSUE TITLE
OS X invalid code signature 

### ISSUE THREAD

**Issue by mikejdoe** [haiwen/seafile-client#673] opened 2015-07-16 12:08 UTC
The latest version of Yosemite fails to validate the code signature of the seafile-client.

**Comment by Chilledheart** [comment] 2015-07-16 13:52
Can you provide more information? Which version of OS X are you using? and what's the seafile client's version?

**Comment by eric11** [comment] 2015-07-16 14:26
I can confirm this issue, running OS X Yosemite 10.10.4. I tested the following sea file client versions and all fail the "identified developer" signature check: 

4.2.8
4.2.7
4.2.5
4.2.0
4.1.6

![screen shot 2015-07-16 at 10 22 16 am](https://cloud.githubusercontent.com/assets/1176078/8725921/04cb4ae2-2ba5-11e5-818e-a1615caf19ed.png)

I realize that I can set my security options to "Allow apps downloaded from: Anywhere", and have done so for now, but this is not a good option for most users.

**Comment by Chilledheart** [comment] 2015-07-17 00:26
It might be because of [an known Apple bug][bug]. I hope I can made a fix today.


[bug]: https://forums.developer.apple.com/thread/7833

**Comment by Chilledheart** [comment] 2015-07-17 03:18
Hi all:

I have found out where it is possible to go wrong and managed to make a fix.
You can try with the HEAD build [here] or you can wait for a new build for version 4.2.8 later.

[here]: https://seacloud.cc/f/8d5492e024/

**Comment by Chilledheart** [comment] 2015-07-17 04:00
@eric11 another workaround for the old packages is to choose the `Seafile Client` application in Finder, right click on it and click `Open` in the popup menu. Then click "Yes" in the dialog.

**Comment by Chilledheart** [comment] 2015-07-17 04:05
the new package is available at https://bintray.com/artifact/download/seafile-org/seafile/seafile-client-4.2.8.1.dmg

**Comment by Chilledheart** [comment] 2015-07-17 04:05
Fixed in https://github.com/haiwen/seafile-client/commit/0316383c603d478ff96d4105f577acebfdf43fb8

**Closed by Chilledheart** 2015-07-17 04:05 UTC
