### ISSUE TITLE
Limit log entries

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#800] opened 2016-05-27 15:27 UTC
There have been quite some reports of too big logs. I think it would be good to limit some log messages (those that just repeat itself all the time without having big value) to e.g. 10 occurences (per seafile client run) and one more line stating that this log message has been disabled.

In addition the client could remove everything that exceeds 10 MiB or  (if that is simpler) everything exceeding e.g. 100000 lines or (another option) being older than x days old on start.

Just recently there were users reporting log sizes from multiple 100 MiB up to 8 GiB.
E.g. https://forum.seafile.de/t/seafile-log-grows-till-disk-is-full/4051/5?u=shoeper

> The old log where 8 GB - https://github.com/haiwen/seafile/issues/1687#issuecomment-225867244

**Comment by shoeper** [comment] 2016-06-03 09:02
https://forum.seafile.de/t/seafile-log-grows-till-disk-is-full/4051/5?u=shoeper

**Comment by wolfcry0** [comment] 2016-06-11 00:53
I've been having a problem with the seafile client filling up my SSD in the span of a few hours because the seafile.log file grows rapidly with this entry:

`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`

According to the windows resource monitor seafile is writing to seafile.log at roughly 2.5MB/s which is a huge amount of data for a log file.

I did a fresh install of version 5.1.2 (removed seafile, removed ccnet folder), but the problem is still there.

This is on a windows 10 x64 system, client version 5.1.2, no AV installed other than windows defender, windows firewall is disabled, MS EMET installed.

Server is centos with version 5.0.7

Last few lines from ccnet.log:

`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 12:27:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 12:27:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 13:47:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 13:47:57] ../common/peer.c(943): Local peer down`
`[06/08/16 15:52:10] ../common/peer.c(943): Local peer down`
`[06/08/16 15:52:10] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 15:52:10] ../common/peer.c(943): Local peer down`

Is there a fix for this? It fills up my disk in less than a day so I cannot use seafile right now.

**Comment by shoeper** [comment] 2016-06-11 23:00
Likely that Emit blocks some of the internal communication. Does Seafile work at all?

**Comment by wolfcry0** [comment] 2016-06-11 23:03
Yes as far as I can tell all my folders sync without any problems

**Comment by shoeper** [comment] 2016-06-29 21:51
https://forum.seafile.de/t/seafile-log-grows-till-disk-is-full/4051/7?u=shoeper

**Comment by shoeper** [comment] 2016-06-29 21:52
https://github.com/haiwen/seafile/issues/805

**Comment by madman2021** [comment] 2016-07-28 20:33
This is serious issue, when connection to the server is unavailable the error from wolfcry0's post at the bottom is spammed that much withing a few hours the log file grew to 42GB filling the rest of my C: drive and causing windows to crash.

**Comment by wolfcry0** [comment] 2016-07-28 20:40
Are you on the latest client available on the website? I updated a few weeks ago and the issue is no longer present.

**Comment by madman2021** [comment] 2016-07-28 22:42
@wolfcry0  Yes 100%. Here  are my steps.

1. Downloaded and ran the setup.sh on a Debian 8.1 VM
2. Started hub and files
3.Connected Windows PC with client downloaded from site last night
4.Synced a 1kb text file as a test to check some features I needed
5. Stopped VM
6. About an hour or so later I got a message about no disk space on my C:\ (SSD).

Checked with WinDirStat and the log file for Seafile was 48GB

**Comment by freeplant** [comment] 2016-07-29 01:57
What messages are repeated in the log?

**Comment by madman2021** [comment] 2016-07-29 21:59
@freeplant This one 
../common/peer.c(943): Local peer down
 ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)

**Comment by freeplant** [comment] 2016-07-29 23:02
Thanks. We will fix it.

**Comment by madman2021** [comment] 2016-08-01 19:22
@freeplant In the last 24 hours the log has used over 80GB

**Comment by madman2021** [comment] 2016-08-01 22:16
@freeplant More info 
d')
[08/01/16 21:16:26] sync-mgr.c(660): Repo 'My Library' sync state transition from 'uploading' to 'initializing'.
[08/01/16 21:16:26] sync-mgr.c(1479): Removing blocks for repo My Library(667e348b).
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] [Job Manager] read pipe error: No error
[08/01/16 22:18:57] wt-monitor-win32.c(565): GetQueuedCompletionStatus failed, error code 64[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] [Job Manager] read pipe error: No error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error
[08/01/16 22:18:57] read pipe error

**Comment by madman2021** [comment] 2016-08-01 22:17
Here is a scary gif of the grow rate 
![6046290](https://cloud.githubusercontent.com/assets/2904531/17310723/16e21fdc-583e-11e6-8188-277c1b69c78c.gif)

**Closed** 2017-02-23 15:51 UTC

**Comment by shoeper** [comment] 2017-02-23 16:43
I'm not sure if this is fully fixed. Afaik the log is still never truncated. It could be a good idea to limit the logsize and automatically remove old entries.

**Comment by moschlar** [comment] 2018-05-08 09:37
Indeed, there still does not seem to be any kind of truncation or rotation of the Seafile client logfiles.
Please implement something like that (and reopen this issue until that is done).
https://github.com/haiwen/seafile/issues/805
