### ISSUE TITLE
Client is attempting to connect to 127.0.0.1

### ISSUE THREAD

**Issue by jeffmikels** [haiwen/seafile-client#965] opened 2017-08-01 05:10 UTC
My client window shows a red chain icon in the lower left... clicking on it shows three accounts. One of them is for 127.0.0.1. I want to delete this account; however, when I click on the avatar icon in the top left, the invalid account does not show up.

![screen shot 2017-08-02 at 4 04 24 pm](https://user-images.githubusercontent.com/3506020/28892789-1bdcf9e2-779d-11e7-8171-27f0d0424fb1.png)

**Comment by jeffmikels** [comment] 2017-08-01 05:14
The 127.0.0.1 account does not exist in the accounts.db file.

**Comment by jeffmikels** [comment] 2017-08-02 20:29
Here's the relevant log entry:

```bash
logs/applet.log:[08/02/17` 15:43:05][api] network error for http://127.0.0.1:8000/media/avatars/8/8/2ac5005b0a5a8099895a2534a06f1d/resized/42/e094ee63ca52e4cd90173474238ea2be.png: Connection refused
```

**Comment by freeplant** [comment] 2017-08-10 00:33
After analysing the source code, we think the problem caused by that the server doesn't have correctly set the SERVICE_URL and FILE_SERVER_ROOT. Can you check it?

The default SERVICE_URL is 127.0.0.1:8000

**Comment by jeffmikels** [comment] 2017-08-10 04:32
Both were properly set in the web settings, but I have now added SERVICE_URL to the seahub_settings.py file.

Nonetheless, the client still attempts to connect to 127.0.0.1.

**Comment by wxr9** [comment] 2017-08-21 09:11
can you tell me how to compile the seafile-client? i have installed qt5 mingw

**Comment by zix99** [comment] 2017-08-25 19:06
This was happening to me, and I suspect because I was using `proxy_pass` in my nginx config rather than fastcgi.  Either way, I added `X-Real-IP` to my configuration, and that seemed to solve it. I also made sure my `SERVICE_URL` and `FILE_SERVER_ROOT` were set correctly. I haven't done the digging to see if it's some combination of them.

I removed much of the non-applicable parts:
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect default;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
}
```

**Comment by F0cks** [comment] 2017-10-01 13:02
Same problem here with apache server and Ubuntu client:
```
[01/10/2017 11:48:14][api] network error for http://127.0.0.1:8000/media/avatars/d/6/eed6d6bd5109c2e3aa610d020d4e90/resized/80/a682103e9b1ee2262fac20d15267f35c.png: Connection refused
```

If I understand correctly @zix99 solution, the problem should be in sites-available configuration, probably near to : 
```
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http//127.0.0.1:8000/
```
![screenshot from 2017-10-01 14-50-00](https://user-images.githubusercontent.com/2871302/31054671-78d56af4-a6b8-11e7-9b07-bedd1bad45d5.jpg)

**Comment by kevinvalk** [comment] 2017-11-06 08:43
@F0cks 
For me, adding the ProxyPreserveHost option solved the problem (see https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost).

**Comment by Bjarno** [comment] 2017-11-06 13:15
Changing the part for Seahub in the Apache configuration to

```
#
# seahub
#
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/
```

fixed the problem for me. So thanks @kevinvalk for mentioning it.

**Comment by Bjarno** [comment] 2017-11-12 21:00
Something I found out is that Seafile (in some circumstances) redirects to a `http` URL (with the same port, if it is passed) when using `ProxyPreserveHost On` (at least for me, see [this thread on the forums](https://forum.seafile.com/t/partially-solved-seafile-server-redirects-to-http-despite-config-set-to-https/4540)). So that is not the solution either.

**Comment by Bjarno** [comment] 2017-11-13 13:29
Possible solution for web clients, when using `ProxyPreserveHost On`...

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

For Apache, add the following to your virtualhost...
`Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"`

31536000 seconds is equal to 1 year.

It's a workaround, but one that also better protects your clients, as your server reports to the browser that http should NEVER be used on that domain (and subdomains). Exclude `includeSubDomains` if you are running things on the same TLD that are only reachable without SSL.

**Comment by lilarcor** [comment] 2017-11-17 08:43
added ProxyPreserveHost On, but donesn't work for https, the log is still showing get avatar failed from http://xxxxxx

**Comment by Bjarno** [comment] 2017-11-17 09:59
Indeed, now that you mention it. The avatars don't load in the client, but the errors disappear.

**Comment by andi-blafasl** [comment] 2017-12-03 23:50
I just upgrade my Client to Version 6.1.3 and hit the 127.0.0.1 error! The Avatar was also missing in the Client.

My Server is using Apache on Ubuntu 16.04 with seafile server 6.2.2 in wsgi mode.

After changing my config like @Bjarno suggested

    ProxyPreserveHost On

the error on the client is resolved and the Avatar is displayed again.

**Comment by lins05** [comment] 2017-12-06 08:28
Should be fixed in https://github.com/haiwen/seafile-client/commit/c5f1268d829ca32c74c4c12b16862f3f24bcb9b1

**Closed by lins05** 2017-12-06 08:28 UTC
Labels: bug
