### ISSUE TITLE
[Bug] "Resync this library" syncs to wrong directory

### ISSUE THREAD

**Issue by Redsandro** [haiwen/seafile-client#1132] opened 2018-09-07 08:12 UTC
* __Seafile Client:__ 6.1.8 (Ubuntu 18.04 x64)

## Steps to reproduce

* Right-click unsynced library (let's say `MyLib`) -> _"Sync this library"_
* Choose _"Sync with an existing folder"_
* Use different name, let's use: `/tmp/MyExistingFolder`
* Let it sync
* Right-click `MyLib` -> _"Resync this library"_

## Expected result

`/tmp/MyExistingFolder` is resynced

## Observed result

A new sync is created and downloaded at `/tmp/MyLib`

---

This definitely solves #1129 and probably solves #1131 too.

**Comment by liar666** [comment] 2022-09-29 07:09
Hi,

Similar bug in seafile-gui 8.0.5-1 (ubuntu jammy): 
- When selecting a seafile "lib" and asking for it to be sync'ed, Seafile appends "/home/user/Seafile" to it, thus resulting in a sync'ed directory that is "/home/user/Seafile/*Seafile*/lib".
- When un-sync'ing the lib, moving the files and re-sync'ing the lib again, the "new" "option to syncing with an existing folder with a different" again adds an unwelcome level of "/Seafile/" in the path.
- In the end if I select the existing directory (moved to the correct path), Seafile client does absolutely nothing: no sync happens, the icon on the right of the lib still shows the empty white cloud, meaning the lib is not sync'ed...

So there are still many bugs related to path where the lib should be stored thus re-opening the issue is mandatory.

**Comment by liar666** [comment] 2022-09-29 07:14
EDIT: seems to be related to the fact that when I close the seafile-applet, it asks again for all the configuration to be done (path , login/pass, etc)/
I did'nt read correctly the text saying a "Seafile" subdir would be automatically created in the dir I will select.

**Comment by killing** [comment] 2023-04-18 07:45
This is fixed by https://github.com/haiwen/seafile-client/pull/1447 and will be released in 9.0.2 version.

**Closed by killing** 2023-04-18 07:45 UTC
Labels: need-test, low-priority
