### ISSUE TITLE
CPU Spike when Interval Set

### ISSUE THREAD

**Issue by david-wolf** [haiwen/seafile-client#780] opened 2016-02-28 00:18 UTC
When setting the Interval to say N seconds the CPU will spike to 8% each time the interval passes on seaf-deamon.  This happens even if no changes have taken place.  If interval is left at its default of 0 no CPU spikes are seen.

I notice that in the UI it will show "indexing files" where as when set to zero this is not shown.  Perhaps has something to do with this.

**Comment by killing** [comment] 2016-02-28 02:40
This is the intended behavior. The client will scan the entire folder no matter there is changes or not. This option is usually used for network drives on Windows, which can't be monitored for changes.

**Comment by killing** [comment] 2016-02-28 02:40
I'll close this since it doesn't look like a bug to me ;-)

**Closed by killing** 2016-02-28 02:40 UTC

**Comment by david-wolf** [comment] 2016-02-28 08:34
Is there anyway to have the client check with the server for changes faster without having to scan its own directory.

**Comment by shoeper** [comment] 2016-03-11 14:41
Yes, setting the intervall to 0 falls back to the default mode which listens on change events from the operating system.
