### ISSUE TITLE
windows: choosing accounts

### ISSUE THREAD

**Issue by ftribrunn** [haiwen/seafile-client#746] opened 2015-11-11 22:42 UTC
if i click on my avatar this comes up:

![image](https://cloud.githubusercontent.com/assets/4007655/11105139/54fb9faa-88cd-11e5-9985-064045669ddf.png)

but if i choose another one, th little popupwindow is right there:

![image](https://cloud.githubusercontent.com/assets/4007655/11105127/39eefad6-88cd-11e5-801f-cbcf5a4ee1b5.png)

I suggest only the 3 (settings, logout, delete) in the submenue.
and the "choose" is just clicking on the account.

greets
fabian

**Comment by liayn** [comment] 2016-01-05 23:30
This is a duplicate of #736, wanna close this one?

**Closed** 2016-01-05 23:31 UTC
Labels: bug
